from app.repository.user import UserRepository
from app.repository.college import CollegeRepository
from app.repository.student import StudentRepository
from app.repository.club import ClubRepository
from app.repository.membership import MembershipRepository
from app.repository.event import EventRepository
from app.repository.event_registration import EventRegistrationRepository
from app.repository.announcement import AnnouncementRepository
from app.repository.issue import IssueRepository
from app.repository.notification import NotificationRepository
from app.repository.certificate import CertificateRepository
from app.repository.leaderboard import LeaderboardRepository