"""added a interest column in Student table

Revision ID: 138b941be66b
Revises: 411e5ba821c4
Create Date: 2026-07-11 23:41:41.641330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '138b941be66b'
down_revision: Union[str, None] = '411e5ba821c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('interests', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'interests')
    # ### end Alembic commands ###