"""notification table

Revision ID: 27fde89f8708
Revises: 0b33d87f9220
Create Date: 2026-07-30 19:03:20.792333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fde89f8708'
down_revision: Union[str, None] = '0b33d87f9220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOIN_APPROVED', 'JOIN_REJECTED', 'REGISTRATION_CONFIRMED', 'RESULT_POSTED', 'CERTIFICATE_ISSUED', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_student_created', 'notifications', ['student_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_student_unread', 'notifications', ['student_id', 'is_read'], unique=False)
    op.create_index('ix_announcements_club_created', 'announcements', ['club_id', 'created_at'], unique=False)
    op.create_index('ix_issues_club_status', 'issues', ['club_id', 'status'], unique=False)
    op.create_index('ix_issues_student_created', 'issues', ['student_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_membership_student_club', 'memberships', ['student_id', 'club_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_membership_student_club', 'memberships', type_='unique')
    op.drop_index('ix_issues_student_created', table_name='issues')
    op.drop_index('ix_issues_club_status', table_name='issues')
    op.drop_index('ix_announcements_club_created', table_name='announcements')
    op.drop_index('ix_notifications_student_unread', table_name='notifications')
    op.drop_index('ix_notifications_student_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###