"""fixed college

Revision ID: 411e5ba821c4
Revises: 5215e36c6614
Create Date: 2026-07-04 20:27:10.921167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411e5ba821c4'
down_revision: Union[str, None] = '5215e36c6614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'roll_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'roll_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###