"""fixed models for user,admin and student

Revision ID: 5215e36c6614
Revises: 286154cd1699
Create Date: 2026-07-04 14:04:06.165722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5215e36c6614'
down_revision: Union[str, None] = '286154cd1699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('campus_admin')
    op.add_column('colleges', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'colleges', ['slug'])
    op.add_column('students', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('roll_no', sa.String(), nullable=False))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('students', 'enrollment_no')
    op.drop_column('students', 'interests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('enrollment_no', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'roll_no')
    op.drop_column('students', 'bio')
    op.drop_constraint(None, 'colleges', type_='unique')
    op.drop_column('colleges', 'slug')
    op.create_table('campus_admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('campus_admin_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campus_admin_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('campus_admin_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('campus_admins')
    # ### end Alembic commands ###