from app.api.auth import auth_router
from app.api.college import college_router
from app.api.student import student_router
from app.api.club import club_router
from app.api.event import event_router
from app.api.announcement import announcement_router
from app.api.issue import issue_router
from app.api.notification import notification_router
from app.api.certificate import certificate_router
from app.api.leaderboard import leaderboard_router
from app.api.ai import ai_router
